### PR TITLE
Added completion for resource-like class

### LINKED ISSUE #181: Add completion for resource-like declarations
As per https://puppet.com/docs/puppet/latest/lang_classes.html#section-x54-1hk-xhb it is possible to do resource-like declarations for Puppet types e.g.

```
class {'apache':
  version => '2.2.21',
}
```

> Resource-like declarations look like normal resource declarations, using the class pseudo-resource type. You can provide a value for any class parameter by specifying it as a resource attribute.

The completion provider should provide parameter and property completions for this type of declaration.

### PR DESCRIPTION
**Pull request by juliosueiras**
Fixes #181 

Added Completion for [resource-like class declare](https://puppet.com/docs/puppet/5.3/lang_classes.html#using-resource-like-declarations)

### CODE REVIEW

**Comment by jpogran** [comment]
Thanks for the PR! We're in the midst of making the Sept release for this extension, so we'll review this for inclusion in that release. We should have a reply back by next week, if not sooner.

**Comment by genebean** [comment]
ooooo, very nice.

**Comment by juliosueiras** [comment]
ok, did a rebase and added more details in the commit message, which part need more details?

**Comment by glennsarti** [comment]
Hey @juliosueiras !!  Thankyou so much for this PR.  I've added some tests and refactored the detection logic to reduce duplication.  Just waiting for the CI to go green and I'll merge.

Again, thankyou so much for taking to time to add this 🙏

**Comment by binford2k** [comment]
I could be wrong, but this looks like a first time community PR! 🎉

@juliosueiras Puppet would love to send you a small token to thank you and welcome you to our community. Can you send an email to community@puppet.com with your mailing address?

**Comment by juliosueiras** [comment]
sure =)

**Pull request merged**
